In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/auto-mpg.csv")

In [ ]:
df.head(2)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320

In [ ]:
df.shape

(398, 9)

In [ ]:
df[["mpg", "weight"]]

      mpg  weight
0    18.0    3504
1    15.0    3693
2    18.0    3436
3    16.0    3433
4    17.0    3449
..    ...     ...
393  27.0    2790
394  44.0    2130
395  32.0    2295
396  28.0    2625
397  31.0    2720

[398 rows x 2 columns]

In [ ]:
df.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model year      0
origin          0
car name        0
dtype: int64

In [ ]:
print(df["mpg"].min)
print(df["mpg"].max)
print(df["mpg"].mean)
print(df["mpg"].std)
print(df["mpg"].var)

<bound method Series.min of 0      18.0
1      15.0
2      18.0
3      16.0
4      17.0
       ...
393    27.0
394    44.0
395    32.0
396    28.0
397    31.0
Name: mpg, Length: 398, dtype: float64>
<bound method Series.max of 0      18.0
1      15.0
2      18.0
3      16.0
4      17.0
       ...
393    27.0
394    44.0
395    32.0
396    28.0
397    31.0
Name: mpg, Length: 398, dtype: float64>
<bound method Series.mean of 0      18.0
1      15.0
2      18.0
3      16.0
4      17.0
       ...
393    27.0
394    44.0
395    32.0
396    28.0
397    31.0
Name: mpg, Length: 398, dtype: float64>
<bound method Series.std of 0      18.0
1      15.0
2      18.0
3      16.0
4      17.0
       ...
393    27.0
394    44.0
395    32.0
396    28.0
397    31.0
Name: mpg, Length: 398, dtype: float64>
<bound method Series.var of 0      18.0
1      15.0
2      18.0
3      16.0
4      17.0
       ...
393    27.0
394    44.0
395    32.0
396    28.0
397    31.0
Name: mpg, Length: 398, dtype: float64>
<bound method Series.median of 0      18.0
1      15.0
2      18.0
3      16.0
4      17.0
       ...
393    27.0
394    44.0
395    32.0
396    28.0
397    31.0
Name: mpg, Length: 398, dtype: float64>

In [ ]:
print(df["mpg"].median)

<bound method Series.median of 0      18.0
1      15.0
2      18.0
3      16.0
4      17.0
       ...
393    27.0
394    44.0
395    32.0
396    28.0
397    31.0
Name: mpg, Length: 398, dtype: float64>

In [ ]:
df.describe()

,mpg,cylinders,displacement,weight,acceleration,model year,origin
count,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000
mean,23.514573,5.454774,193.425879,2970.424623,15.568090,76.010050,1.572864
std,7.815984,1.701004,104.269838,846.841774,2.757689,3.697627,0.802055
min,9.000000,3.000000,68.000000,1613.000000,8.000000,70.000000,1.000000
25%,17.500000,4.000000,104.250000,2223.750000,13.825000,73.000000,1.000000
50%,23.000000,4.000000,148.500000,2803.500000,15.500000,76.000000,1.000000
75%,29.000000,8.000000,262.000000,3608.000000,17.175000,79.000000,2.000000
max,46.600000,8.000000,455.000000,5140.000000,24.800000,82.000000,3.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    object
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model year    398 non-null    int64
 7   origin        398 non-null    int64
 8   car name      398 non-null    object
dtypes: float64(3), int64(4), object(2)
memory usage: 28.1+ KB

In [ ]:
df[df["mpg"]>45]["car name"]

322    mazda glc
Name: car name, dtype: object

In [ ]:
df[df["mpg"]==df["mpg"].min()]["car name"]

28    hi 1200d
Name: car name, dtype: object

In [ ]:
new_df = df[["car name", "weight"]]
new_df.to_csv("new_df.csv")

In [ ]:
new_df = df[["car name", "weight"]]
new_df_2 = df[["weight", "car name"]]

In [ ]:
new_df_2.head(1)

   weight                   car name
0    3504  chevrolet chevelle malibu

In [ ]:
g = df.groupby("model year")
print (g)
g.max()

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x7f13165113d0>

,mpg,cylinders,displacement,horsepower,weight,acceleration,origin,car name
model year,,,,,,,,
70,27.0,8,455.0,97,4732,20.5,3,volkswagen 1131 deluxe sedan
71,35.0,8,400.0,?,5140,20.5,3,volkswagen model 111
72,28.0,8,429.0,97,4633,23.5,3,volvo 145e (sw)
73,29.0,8,455.0,95,4997,21.0,3,volvo 144ea
74,32.0,8,350.0,?,4699,21.0,3,volkswagen dasher
75,33.0,8,400.0,98,4668,21.0,3,volvo 244dl
76,33.0,8,351.0,95,4380,22.2,3,vw rabbit
77,36.0,8,400.0,98,4335,19.0,3,volkswagen rabbit custom
78,43.1,8,318.0,97,4080,21.5,3,volvo 264gl
79,37.3,8,360.0,90,4360,24.8,3,vw rabbit custom
80,46.6,6,225.0,?,3381,23.7,3,vw rabbit c (diesel)
81,39.1,8,350.0,?,3725,20.7,3,volvo diesel
82,44.0,6,262.0,?,3035,24.6,3,vw pickup

In [ ]:
df["cylinders"].unique()

array([8, 4, 6, 3, 5])

In [ ]:
df["cylinders"].value_counts()

cylinders
4    204
8    103
6     84
3      4
5      3
Name: count, dtype: int64

In [ ]:
car_new = df.drop(["origin", "car name"], axis=1)
car_new.describe()

,mpg,cylinders,displacement,weight,acceleration,model year
count,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000
mean,23.514573,5.454774,193.425879,2970.424623,15.568090,76.010050
std,7.815984,1.701004,104.269838,846.841774,2.757689,3.697627
min,9.000000,3.000000,68.000000,1613.000000,8.000000,70.000000
25%,17.500000,4.000000,104.250000,2223.750000,13.825000,73.000000
50%,23.000000,4.000000,148.500000,2803.500000,15.500000,76.000000
75%,29.000000,8.000000,262.000000,3608.000000,17.175000,79.000000
max,46.600000,8.000000,455.000000,5140.000000,24.800000,82.000000